/**
 * Lenpli
 * Sistema monitoreo y control 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package co.vaale.bankpayment.h2h.model


/**
 * Datos del pagador
 * @param name Nombre de la empresa pagadora
 * @param documentNumber Identificación del beneficiario
 * @param documentType Tipo de cuenta del beneficiario
 * @param accountNumber Número de cuenta del beneficiario
 * @param accountType Tipo de cuenta del beneficiario
 * @param bank Banco del beneficiario
 * @param amount Valor
 * @param concept Concepto
 * @param email Email
 * @param transactionType Tipo de transacción
 * @param applicationdate Fecha de aplicación
 */
data class H2hRecipient (

    /* Nombre de la empresa pagadora */
    val name: kotlin.String? = null,
    /* Identificación del beneficiario */
    val documentNumber: kotlin.String? = null,
    /* Tipo de cuenta del beneficiario */
    val documentType: kotlin.Int? = null,
    /* Número de cuenta del beneficiario */
    val accountNumber: kotlin.String? = null,
    /* Tipo de cuenta del beneficiario */
    val accountType: kotlin.String? = null,
    /* Banco del beneficiario */
    val bank: kotlin.Int? = null,
    /* Valor */
    val amount: kotlin.Double? = null,
    /* Concepto */
    val concept: kotlin.String? = null,
    /* Email */
    val email: kotlin.String? = null,
    /* Tipo de transacción */
    val transactionType: kotlin.Int? = null,
    /* Fecha de aplicación */
    val applicationdate: kotlin.String? = null
) {
}