/**
 * Lenpli
 * Sistema monitoreo y control 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Datos del pagador
 * @param commercePlaceId Identificador único
 * @param commercePlaceName Nombre comercio
 * @param totalSalesAmount Monto
 * @param countSubscriptionPlanPayment Cantidad de cobros de cuota
 * @param premiumMembershipCapValue Tope de la membresia
 * @param minPremiumMembershipCapValue Valor mínimo de la membresía
 * @param premiumMembershipValue Valor de la membresía
 */
data class PaymentMembership (

    /* Identificador único */
    var commercePlaceId: kotlin.Long? = null,
    /* Nombre comercio */
    var commercePlaceName: kotlin.String? = null,
    /* Monto */
    var totalSalesAmount: kotlin.Double? = null,
    /* Cantidad de cobros de cuota */
    var countSubscriptionPlanPayment: kotlin.Int? = null,
    /* Tope de la membresia */
    var premiumMembershipCapValue: kotlin.Double? = null,
    /* Valor mínimo de la membresía */
    var minPremiumMembershipCapValue: kotlin.Double? = null,
    /* Valor de la membresía */
    var premiumMembershipValue: kotlin.Double? = null
) {
}